### ISSUE TITLE
wx_force_option_off doesn't work on first configuration

### ISSUE THREAD

**Issue by alamaison** [tibogens/wxWidgets-cmake#8]
`wx_force_option_off` doesn't set the correct variable to off.  For example, when `INOTIFY` and `KQUEUE` are missing, `wx_force_option_off` is called to set the `wxUSE_FSWATCHER` variable to `OFF`.  However, it actually sets `WXSETUP_wxUSE_FSWATCHER` to OFF, which means that the configure check in `unix/chkconf.h` fails:
```c
#if wxUSE_FSWATCHER
#   if !defined(wxHAS_INOTIFY) && !defined(wxHAS_KQUEUE)
#       ifdef wxABORT_ON_CONFIG_ERROR
#           error "wxFileSystemWatcher requires either inotify() or kqueue()"
#       else
#           undef wxUSE_FSWATCHER
#           define wxUSE_FSWATCHER 0
#       endif
#   endif
#endif /* wxUSE_FSWATCHER */
```

If I run configure a second time, the function seems to work and `wxUSE_FSWATCHER` is disabled in the setup file.  I'm not sure what the correct solution is here, so I haven't provided a pull request.

**Comment by tibogens** [comment]
I can't really wrap my head around the way I had designed this. I recall that WXSETUP_wxUSE_xxx options are indeed converted into wxUSE_xxx at some point, but not exactly when and how. I think this issue is too minor to deserve too much attention right now - we can see that at RC stage, not beta.
Thoughts?

**Comment by alamaison** [comment]
I don't know that I'd call it minor.  Every new user's build will fail, unless they happen to configure twice.  CI builds have to run `cmake` twice to get a positive result.  That seems pretty broken.

**Comment by tibogens** [comment]
Sorry, since you didn't mention the platform, compiler & port, I did not even think you could be affected systematically. On Windows (both MSVC and MinGW/gcc) everything is OK. I haven't had the change to test with other toolchains/ports/platforms yet.
So: could you please update the wiki (https://github.com/tibogens/wxWidgets-cmake/wiki/Build%20Matrix) reporting your build environment and making a reference to this issue in the Remarks column?
As soon as I have time to get my hand onto a setup similar as yours I can work on the issue.

**Comment by tibogens** [comment]
Actually I don't know if you have write access to the wiki. If you don't, then simply report your setup in this issue, I'll update the wiki.

**Comment by alamaison** [comment]
Sorry, this was on Ubuntu 12.04, gcc 4.6.3 using the GTK port with GTK 2.0.  You can see the log on Travis CI and I can reproduce this locally: https://travis-ci.org/alamaison/wxWidgets/jobs/55574286

**Comment by alamaison** [comment]
I don't think I have wiki edit permission

**Comment by tibogens** [comment]
0e21264f6a45b62e59049fe3479b617514dafd33 should have fixed this. Tell me if you have a chance to test. - thx

**Comment by alamaison** [comment]
Looks good: https://travis-ci.org/alamaison/wxWidgets/jobs/56306524.  Thanks
